#--Mappings--
dest_country = {'Albania','Antigua and Barbuda','Aruba','Barbados','Belgium','Bermuda','Bosnia and Herzegovina','British Virgin Islands','Bulgaria','Caribbean Netherlands','Cayman Islands','Colombia','Croatia','Cuba','Curacao','Denmark','Dominica','Dominican Republic',
                'Estonia','Faroe Islands','Finland','France','Georgia','Germany','Greece','Grenada','Guadeloupe','Guernsey','Haiti','Iceland','Ireland','Isle of Man','Italy','Jamaica','Jersey','Latvia','Lithuania','Malta','Martinique','Monaco','Montenegro','Morocco','Netherlands','Norway',
                'Poland','Portugal','Puerto Rico','Romania','Russia','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Slovenia','Spain','Svalbard','Sweden','The Bahamas','Tunisia','Turkey','Turks and Caicos Islands','U.S. Virgin Islands',
                'Ukraine','United Kingdom',
}

#####
port_country = {'Albania','Antigua and Barbuda','Aruba','Barbados','Belgium','Bermuda','Bosnia and Herzegovina','British Virgin Islands','Bulgaria','Caribbean Netherlands','Cayman Islands','Colombia','Croatia','Cuba','Curacao','Denmark','Dominica','Dominican Republic',
                'Estonia','Faroe Islands','Finland','France','Georgia','Germany','Greece','Grenada','Guadeloupe','Guernsey','Haiti','Iceland','Ireland','Isle of Man','Italy','Jamaica','Jersey','Latvia','Lithuania','Malta','Martinique','Monaco','Montenegro','Morocco','Netherlands','Norway',
                'Poland','Portugal','Puerto Rico','Romania','Russia','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Slovenia','Spain','Svalbard','Sweden','The Bahamas','Tunisia','Turkey','Turks and Caicos Islands','U.S. Virgin Islands',
                'Ukraine','United Kingdom','United States'
}

#####
tld_country = {'Albania':'.al','Antigua and Barbuda':'.ag','Aruba':'.aw','Barbados':'.bb','Belgium':'.be','Bermuda':'.bm','Bosnia and Herzegovina':'.ba','British Virgin Islands':'.vg','Bulgaria':'.bg','Caribbean Netherlands':'.bq',
               'Cayman Islands':'.ky','Colombia':'.co','Croatia':'.hr','Cuba':'.cu','Curacao':'.cw','Denmark':'.dk','Dominica':'.dm','Dominican Republic':'.do','Estonia':'.ee','Faroe Islands':'.fo','Finland':'.fi','France':'.fr','Georgia':'.ge','Germany':'.de',
               'Greece':'.gr','Grenada':'.gd','Guadeloupe':'.gp','Guernsey':'.gg','Haiti':'.ht','Iceland':'.is','Ireland':'.ie','Isle of Man':'.im','Italy':'.it','Jamaica':'.jm','Jersey':'.je','Latvia':'.lv','Lithuania':'.lt','Malta':'.mt','Martinique':'.mq',
               'Principality of Monaco':'.mc','Montenegro':'.me','Morocco':'.ma','Netherlands':'.nl','Norway':'.no','Poland':'.pl','Portugal':'.pt','Puerto Rico':'.pr','Romania':'.ro','Russia':'.ru','Saint Kitts and Nevis':'.kn','Saint Lucia':'.lc',
               'Saint Vincent and the Grenadines':'.vc','Slovenia':'.si','Spain':'.es','Svalbard':'.sj','Sweden':'.se','Bahamas':'.bs','Tunisia':'.tn','Turkey':'.tr','Turks and Caicos Islands':'.tc','U.S. Virgin Islands':'.vi','Ukraine':'.ua',
               'United Kingdom':'.uk','United States':'.com',

#####
}

######
locale = {'Albania':'sq_AL','Antigua and Barbuda':'en_AG','Aruba':'nl_AW','Barbados':'en_BB','Belgium':'de_BE','Bermuda':'en_BM','Bosnia and Herzegovina':'bs_BA','British Virgin Islands':'en_VG','Bulgaria':'bg_BG',
          'Caribbean Netherlands':'nl_BQ','Cayman Islands':'en_KY','Colombia':'es_CO','Croatia':'hr_HR','Cuba':'es_CU','Curacao':'en_CW','Denmark':'da_DK','Dominica':'en_DM','Dominican Republic':'es_DO','Estonia':'et_EE',
          'Faroe Islands':'fo_FO','Finland':'fi_FI','France':'fr_FR','Georgia':'ka_GE','Germany':'de_DE','Greece':'el_GR','Grenada':'en_GD','Guadeloupe':'fr_GP','Guernsey':'en_GG','Haiti':'fr_HT','Iceland':'is_IS','Ireland':'en_IE',
          'Isle of Man':'en_IM','Italy':'it_IT','Jamaica':'en_JM','Jersey':'en_JE','Latvia':'lv_LV','Lithuania':'lt_LT','Malta':'en_MT','Martinique':'fr_MQ','Principality of Monaco':'fr_MC','Montenegro':'bs_ME','Morocco':'ar_MA',
          'Netherlands':'nl_NL','Norway':'nb_NO','Poland':'pl_PL','Portugal':'pt_PT','Puerto Rico':'en_PR','Romania':'ro_RO','Russia':'ru_RU','Saint Kitts and Nevis':'en_KN','Saint Lucia':'en_LC','Saint Vincent and the Grenadines':'en_VC',
          'Slovenia':'sl_SI','Spain':'es_ES','Svalbard':'no_SJ','Sweden':'sv_SE','Bahamas':'en_BS','Tunisia':'ar_TN','Turkey':'tr_TR','Turks and Caicos Islands':'en_TC',
          'U.S. Virgin Islands':'en_VI','Ukraine':'uk_UA','United Kingdom':'en_GB','United States':'en_US',
}

#####
port_loc = {'Albania':'Durres','Albania':'Shengjin','Albania':'Vlores','Antigua and Barbuda':'St Johns','Aruba':'Paarden Baai - (Oranjestad)','Aruba':'Sint Nicolaas Baai','Bahamas':'Clifton Pier','Bahamas':'Cockburn Town','Bahamas':'Matthew Town',
            'Bahamas':'Nassau','Bahamas':'South Riding Point','Barbados':'Bridgetown','Belgium':'Antwerpen','Belgium':'Bruges','Belgium':'Bruxelles','Belgium':'Ghent','Belgium':'Nieuwpoort','Belgium':'Oostende','Belgium':'Zeebrugge','Bermuda':'Freeport','Bermuda':'Hamilton',
            'Bermuda':'Ireland Island','Bermuda':'St George','Bosnia and Herzegovina':'Neum','Bulgaria':'Burgas','Bulgaria':'Varna','Caribbean Netherlands':'Goto Oil Terminal','Caribbean Netherlands':'Kralendijk','Caribbean Netherlands':'Oranjestad',
            'Caribbean Netherlands':'Salina','Colombia':'Barranquilla','Colombia':'Buenaventura','Colombia':'Cartagena','Colombia':'Covenas','Colombia':'Covenas Offshore Term.','Colombia':'El Bosque','Colombia':'Mamonal','Colombia':'Pozos Colorados','Colombia':'Puerto Bolivar',
            'Colombia':'Puerto Prodeco','Colombia':'San Andres Island','Colombia':'Santa Marta','Colombia':'Tumaco','Colombia':'Turbo','Croatia':'Bakar','Croatia':'Dubrovnik','Croatia':'Dugi Rat','Croatia':'Korcula','Croatia':'Omisalj','Croatia':'Ploce','Croatia':'Pula',
            'Croatia':'Rijeka Luka','Croatia':'Rovinj','Croatia':'Senj','Croatia':'Sibenik','Croatia':'Split','Croatia':'Umag','Croatia':'Zadar','Croatia':'Zaliv Rasa','Cuba':'Antilla','Cuba':'Bahai De La Habana','Cuba':'Bahia De Sagua De Tanamo','Cuba':'Bahia Honda',
            'Cuba':'Banes','Cuba':'Baracoa','Cuba':'Cabanas','Cuba':'Caibarien','Cuba':'Cardenas','Cuba':'Casilda','Cuba':'Cayo Moa Grande','Cuba':'Ceiba Hueca','Cuba':'Cienfuegos','Cuba':'Felton','Cuba':'Guayabal','Cuba':'Isabela De Sagua','Cuba':'Jucaro','Cuba':'Manati',
            'Cuba':'Manzanillo','Cuba':'Mariel','Cuba':'Matanzas','Cuba':'Media Luna','Cuba':'Nicaro','Cuba':'Nueva Gerona','Cuba':'Nuevitas Bay','Cuba':'Palo Alto','Cuba':'Preston','Cuba':'Puerto Guantanamo','Cuba':'Puerto Padre','Cuba':'Santa Cruz del Sur','Cuba':'Santa Lucia',
            'Cuba':'Santiago De Cuba','Cuba':'Tunas De Zaza','Cuba':'Vita','Curacao':'Bullen Baai','Curacao':'Caracasbaai','Curacao':'Sint Michelsbaai','Curacao':'Willemstad','Denmark':'Abenra','Denmark':'Alborg','Denmark':'Arhus','Denmark':'Assens','Denmark':'Augustenborg','Denmark':'Bandholm','Denmark':'Christianso Harbor',
            'Denmark':'Ensted','Denmark':'Esbjerg','Denmark':'Faborg','Denmark':'Fakse Ladeplads Havn','Denmark':'Fredericia','Denmark':'Frederikshavn','Denmark':'Frederikssund','Denmark':'Frederiksvaerk','Denmark':'Grenaa Havn','Denmark':'Gulfhaven','Denmark':'Haderslev','Denmark':'Hadsund','Denmark':'Hals','Denmark':'Hanstholm',
            'Denmark':'Hasle','Denmark':'Helsingor','Denmark':'Hirtshals','Denmark':'Hobro','Denmark':'Holbaek','Denmark':'Holstebro-Stuer','Denmark':'Horsens','Denmark':'Hundested Havn','Denmark':'Kalundborg','Denmark':'Kerteminde','Denmark':'Kobenhavn','Denmark':'Koge','Denmark':'Kolding','Denmark':'Korsor',
            'Denmark':'Kyndbyvaerkets','Denmark':'Lemvig','Denmark':'Mariager','Denmark':'Marstal','Denmark':'Middelfart','Denmark':'Naestved','Denmark':'Nakskov','Denmark':'Nekso','Denmark':'Nyborg','Denmark':'Nykobing','Denmark':'Nykobing (Mor)','Denmark':'Nysted','Denmark':'Odense','Denmark':'Randers',
            'Denmark':'Ringkobing','Denmark':'Rodby Havn','Denmark':'Ronne','Denmark':'Rudkobing','Denmark':'Sakskobing','Denmark':'Skaelskor','Denmark':'Skaerbaek','Denmark':'Skagen Havn','Denmark':'Sonderborg','Denmark':'Stege','Denmark':'Stigsnaesvaerket','Denmark':'Stubbekobing','Denmark':'Studstrup',
            'Denmark':'Svendborg','Denmark':'Thisted','Denmark':'Thyboron','Denmark':'Tuborg','Denmark':'Vejle','Denmark':'Vordingborg','Dominica':'Portsmouth','Dominica':'Roseau','Dominican Republic':'Amber Cove','Dominican Republic':'Andres (Andres Lng Terminal)','Dominican Republic':'Cabo Rojo',
            'Dominican Republic':'La Romana','Dominican Republic':'Las Calderas','Dominican Republic':'Pepillo Salcedo','Dominican Republic':'Puerto De Haina','Dominican Republic':'Puerto Plata','Dominican Republic':'Puerto Viejo De Azua','Dominican Republic':'San Pedro De Macoris','Dominican Republic':'Sanchez',
            'Dominican Republic':'Santa Barbara De Samana','Dominican Republic':'Santa Cruz De Barahona','Dominican Republic':'Santo Domingo','Estonia':'Bekkeri','Estonia':'Heltermaa','Estonia':'Kunda','Estonia':'Lahesuu','Estonia':'Loksa','Estonia':'Meeruse','Estonia':'Miiduranna','Estonia':'Muuga-Port of Tallin',
            'Estonia':'Osmussaar','Estonia':'Paldiski Lounasadam','Estonia':'Paldiski Pohjasadam','Estonia':'Paljassaare','Estonia':'Parnu','Estonia':'Rohukula','Estonia':'Roomassaare','Estonia':'Saaremaa sadam','Estonia':'Sillamae','Estonia':'Vanasadam - Port of Tallinn','Estonia':'Vene-Balti','Estonia':'Virtsu',
            'Faroe Islands':'Fuglafjordur','Faroe Islands':'Klaksvik','Faroe Islands':'Runavik','Faroe Islands':'Sorvagur','Faroe Islands':'Torshavn','Faroe Islands':'Tvoroyri','Faroe Islands':'Vagur','Faroe Islands':'Vestmanna','Finland':'Ekenas','Finland':'Hamina','Finland':'Hanko','Finland':'Hellnas','Finland':'Helsinki',
            'Finland':'Himanka','Finland':'Inkoo','Finland':'Jussaro','Finland':'Kantlax','Finland':'Kaskinen','Finland':'Kemi','Finland':'Kokkola','Finland':'Kotka','Finland':'Kristinestad','Finland':'Loviisa','Finland':'Mantyluoto','Finland':'Mariehamn','Finland':'Naantali','Finland':'Nykarleby','Finland':'Oulu','Finland':'Pargas',
            'Finland':'Pietarsaari','Finland':'Pori','Finland':'Porkkala','Finland':'Porvoo','Finland':'Raahe','Finland':'Rahja','Finland':'Rauma','Finland':'Tahkoluoto','Finland':'Tolkkinen','Finland':'Tornio','Finland':'Turku','Finland':'Uto','Finland':'Uusikaupunki','Finland':'Vaasa','Finland':'Veitsiluoto','France':'Ambes',
            'France':'Antibes','France':'Bastia','France':'Bayonne','France':'Blaye','France':'Bonifacio','France':'Bordeaux','France':'Boulogne-Sur-Mer','France':'Calais','France':'Calvi','France':'Cannes','France':'Concarneau','France':'Deauville','France':'Dieppe','France':'Donges','France':'Dunkerque Port Est',
            'France':'Dunkerque Port Ouest','France':'Fecamp','France':'Fos','France':'Granville','France':'Gravelines','France':'Honfleur','France':"L'ile Rousse",'France':'La Pallice','France':'La Rochelle','France':'Le Legue','France':'Le Treport','France':'Le Verdon','France':"Les Sables D' Olonne",
            'France':'Lezardrieux','France':'Lorient','France':'Marseille','France':'Montoir','France':'Morlaix','France':'Nantes','France':'Nice','France':'Ouistreham','France':'Paimpol','France':'Pauillac','France':'Pontrieux','France':"Port D' Ajaccio",'France':'Port De Caen','France':'Port De Propriano',
            'France':'Port De Roscoff-Bloscon','France':'Port Of Le Havre','France':'Port Of Rouen','France':'Port Saint Louis Du Rhone','France':'Port-de-Bouc','France':'Port-La-Nouvelle','France':'Port-Vendres','France':'Porto Vecchio','France':'Rade De Brest','France':'Rade De Cherbourg','France':'Rochefort',
            'France':'Saint-Malo','France':'Saint-Raphael','France':'Saint-Tropez','France':'Saint-Valery-Sur-Somme','France':'Sete','France':'St Nazaire','France':'Tonnay Charente','France':'Toulon','France':'Treguier','France':'Villefranche','Georgia':'Batumi','Georgia':'Sokhumi','Georgia':'Supsa Marine Terminal',
            'Germany':'Brake','Germany':'Bremen','Germany':'Bremerhaven','Germany':'Brunsbuttel Canal Terminals','Germany':'Brunsbuttel Elbahafen','Germany':'Busum','Germany':'Butzfleth','Germany':'Cuxhaven','Germany':'Eckernforde','Germany':'Elsfleth','Germany':'Emden','Germany':'Flensburg','Germany':'Gluckstadt',
            'Germany':'Hamburg','Germany':'Heiligenhafen','Germany':'Helgoland','Germany':'Husum','Germany':'Itzehoe','Germany':'Kappeln','Germany':'Kiel','Germany':'Leer','Germany':'Lubeck','Germany':'Lubeck-Travemunde','Germany':'Neuhaus','Germany':'Neustadt','Germany':'Nordenham','Germany':'Oldenburg','Germany':'Orth',
            'Germany':'Papenburg','Germany':'Rendsburg','Germany':'Rostock','Germany':'Sassnitz','Germany':'Stralsund','Germany':'Wilhelmshaven','Germany':'Wismar','Germany':'Wolgast','Greece':'Achladi','Greece':'Aigio','Greece':'Alexandroupoli','Greece':'Andros','Greece':'Argostolion','Greece':'Astakos','Greece':'Ayios Nikolaos',
            'Greece':'Gavrio','Greece':'Iraklion','Greece':'Itea','Greece':'Kalamata','Greece':'Kali Limenes','Greece':'Kalimnos','Greece':'Katakolon','Greece':'Kavala','Greece':'Kerkira','Greece':'Khios','Greece':'Kymassi','Greece':'Lagos','Greece':'Lakki','Greece':'Lavrio','Greece':'Limin Kos','Greece':'Limin Sirou','Greece':'Megara Oil Terminal',
            'Greece':'Mesolongion','Greece':'Mikonos','Greece':'Milos','Greece':'Mitilini','Greece':'Navplio','Greece':'Neon Karlovas','Greece':'Nisos Naxos','Greece':'Ormos Aliveriou','Greece':'Patrai','Greece':'Pilos','Greece':'Piraievs','Greece':'Pithagorion','Greece':'Plomarion','Greece':'Preveza','Greece':'Rethimnon','Greece':'Rodhos',
            'Greece':'Samos','Greece':'Sitia','Greece':'Soudha','Greece':'Stratoni','Greece':'Thessaloniki','Greece':'Tsingeli','Greece':'Volos','Greece':'Yerakini','Greece':'Yithion','Grenada':"St George's",'Guadeloupe':'Basse Terre','Guadeloupe':'Gustavia','Guadeloupe':'Pointe A Pitre','Guadeloupe':'Port Louis','Guernsey':'Alderney Harbour',
            'Guernsey':'Saint Peter Port','Guernsey':'Saint Sampson','Haiti':'Cap Haitien','Haiti':'Jacmel','Haiti':'Miragoane','Haiti':'Petit Goave','Haiti':'Port Au Prince','Morocco':'El Jadida','Morocco':'El Jorf Lasfar','Morocco':'Essaouira','Morocco':'Kenitra','Morocco':'Mohammedia','Morocco':'Port D Al Hoceima','Morocco':'Port Nador',
            'Morocco':'Safi','Morocco':'Tanger','Morocco':'Tangier-Mediterranean','Netherlands':'Amsterdam','Netherlands':'Delfzijl','Netherlands':'Den Helder','Netherlands':'Dordrecht','Netherlands':'Eemshaven','Netherlands':'Europoort','Netherlands':'Hansweert','Netherlands':'Harlingen','Netherlands':'Hoek Van Holland','Netherlands':'Ijmuiden',
            'Netherlands':'Maassluis','Netherlands':'Rotterdam','Netherlands':'Scheveningen','Netherlands':'Schiedam','Netherlands':'Terneuzen','Netherlands':'Vlaardingen','Netherlands':'Vlissingen','Netherlands':'Zaandam','Norway':'Akrahamn','Norway':'Alesund','Norway':'Alta','Norway':'Andalsnes','Norway':'Andenes','Norway':'Ardalstangen',
            'Norway':'Arendal','Norway':'Ballstad','Norway':'Batsfjorden','Norway':'Berg','Norway':'Bergen','Norway':'Berlevag','Norway':'Bodo','Norway':'Brattholmen','Norway':'Bredvik','Norway':'Brettesnes','Norway':'Brevik','Norway':'Bronnoysund','Norway':'Bud','Norway':'Djupviken','Norway':'Drag','Norway':'Drammen','Norway':'Drobak',
            'Norway':'Egersund','Norway':'Espevaer','Norway':'Fagerstrand','Norway':'Farsund','Norway':'Fauske','Norway':'Fiborgtangen','Norway':'Finnsnes','Norway':'Flekkefjorden','Norway':'Floro','Norway':'Fredrikstad','Norway':'Gibostad','Norway':'Glomfjord','Norway':'Haakonsvern','Norway':'Halden','Norway':'Hammerfest',
            'Norway':'Hareid','Norway':'Haroysund','Norway':'Harstad','Norway':'Haugesund','Norway':'Hemnesberget','Norway':'Henningsvaer','Norway':'Holmestrand','Norway':'Hommelvik','Norway':'Honningsvag','Norway':'Horten','Norway':'Husnes','Norway':'Jossingfjord','Norway':'Kambo','Norway':'Karsto','Norway':'Kirkehamn',
            'Norway':'Kirkenes','Norway':'Kjerringoy','Norway':'Kjollefjorden','Norway':'Kopervik','Norway':'Korsnes','Norway':'Kragero','Norway':'Kristiansand','Norway':'Kristiansund','Norway':'Kvalsund','Norway':'Lakselv','Norway':'Langstein','Norway':'Larvik','Norway':'Leirvik','Norway':'Levanger','Norway':'Lilandsgrunnen',
            'Norway':'Litle Ballangen','Norway':'Lodingen','Norway':'Malm','Norway':'Maloy','Norway':'Mandal','Norway':'Medby','Norway':'Mehamnfjorden','Norway':'Meling','Norway':'Mo I Rana','Norway':'Molde','Norway':'Moldtustranda','Norway':'Mongstad','Norway':'Mosjoen','Norway':'Moss','Norway':'Mosterhamn','Norway':'Muruvik',
            'Norway':'Namsos','Norway':'Narvik','Norway':'Nesna','Norway':'Norheimsund','Norway':'Odda','Norway':'Oksfjord','Norway':'Olavsvern','Norway':'Ornes','Norway':'Orstav','Norway':'Oslo','Norway':'Porsgrunn','Norway':'Reine','Norway':'Rekefjord','Norway':'Risor','Norway':'Rognan','Norway':'Rorvik','Norway':'Sagvag','Norway':'Salsbruket',
            'Norway':'Sandefjorden','Norway':'Sandnes','Norway':'Sandnessjoen','Norway':'Sarpsborg','Norway':'Sauda','Norway':'Sjovegan','Norway':'Skien','Norway':'Skrova Havn','Norway':'Skudeneshavn','Norway':'Slagenstangen','Norway':'Sortland','Norway':'Sorvaer','Norway':'Stamsund','Norway':'Stavanger','Norway':'Steinkjer','Norway':'Stokkmarknes',
            'Norway':'Storsteilene','Norway':'Strandvik','Norway':'Stura','Norway':'Stusvik','Norway':'Sunndalsora','Norway':'Svelvik','Norway':'Svolvaer','Norway':'Talvik','Norway':'Tananger','Norway':'Thamshamm','Norway':'Tjotta','Norway':'Tofte','Norway':'Tonsberg','Norway':'Tranneset','Norway':'Tranoy','Norway':'Tromso','Norway':'Trondheim',
            'Norway':'Tvedestrand','Norway':'Ulvik','Norway':'Vadso','Norway':'Vaksdal','Norway':'Valloy','Norway':'Vardo','Poland':'Darlowo','Poland':'Gdansk','Poland':'Gdynia','Poland':'Kolobrzeg','Poland':'Nowy Port','Poland':'Police','Poland':'Port Polnochny','Poland':'Swinoujscie','Poland':'Szczecin','Poland':'Ustka','Portugal':'Angra Do Heroismo',
            'Portugal':'Aveiro','Portugal':'Faro','Portugal':'Figueira Da Foz','Portugal':'Funchal','Portugal':'Horta','Portugal':'Lajes','Portugal':'Lisboa','Portugal':'Oporto','Portugal':'Ponta Delgada','Portugal':'Porto De Leixoes','Portugal':'Praia De Vitoria','Portugal':'Setubal','Portugal':'Sines','Portugal':'Viana Do Castelo','Portugal':'Vila Do Porto',
            'Portugal':'Vila Real De S Antonio','Puerto Rico':'Aguadilla','Puerto Rico':'Arecibo','Puerto Rico':'Arroyo','Puerto Rico':'Bahia De Fajardo','Puerto Rico':'Bahia De Jobos','Puerto Rico':'Ensenada Honda','Puerto Rico':'Las Mareas','Puerto Rico':'Mayaguez','Puerto Rico':'Playa De Guanica','Puerto Rico':'Playa De Guayanilla','Puerto Rico':'Playa De Humacao',
            'Puerto Rico':'Playa De Ponce','Puerto Rico':'Puerto Yabucoa','Puerto Rico':'San Juan','Romania':'Basarabi','Romania':'Braila','Romania':'Cernavoda','Romania':'Constanta','Romania':'Danube-Black Sea Canal','Romania':'Galati','Romania':'Mangalia','Romania':'Medgidia','Romania':'Midia','Romania':'Sulina','Romania':'Tulcea','Russia':'Adler','Russia':'Aleksandrovsk -Sakhalinskiy',
            'Russia':'Anapa','Russia':"Arkhangels'k",'Russia':'Azov','Russia':'Baltiysk','Russia':'Bolshaya Piryu Guba','Russia':'Bukhta Gaydamak','Russia':'Bukhta Nagayeva (Magadan)','Russia':'Bukhta Vanino','Russia':'De Kastri','Russia':'Dudinka','Russia':'Gavan Vysotsk','Russia':'Gelendzhik','Russia':'Igarka','Russia':'Kaliningrad','Russia':'Kandalaksha','Russia':'Kavkaz Oil Terminal',
            'Russia':'Kholmsk','Russia':'Korsakov','Russia':'Kronshtadt','Russia':'Lazarev','Russia':'Lesogorsk','Russia':'Lomonosov','Russia':'Mezen','Russia':'Moskal Vo','Russia':'Murmansk','Russia':'Mys Abram','Russia':'Mys Rogatyy Oktyabrskiy','Russia':'Nakhodka','Russia':'Nevelsk','Russia':'Nikol Skoye','Russia':'Nikolayevsk Na Amur','Russia':'Novorossiysk','Russia':'Okhotsk Iy Reyd',
            'Russia':'Ostrovnoy Gremikha','Russia':'Petropavlovsk','Russia':'Pevek','Russia':'Poronaysk','Russia':'Port Beringovsky','Russia':'Port Dikson','Russia':"Pos'yet",'Russia':'Primorsk','Russia':'Provideniya','Russia':'Rabocheostrovsk','Russia':'Rostov-Na-Donu','Russia':'Sankt-Peterburg','Russia':'Severodvinsk','Russia':'Shakhtersk','Russia':'Shakotan','Russia':'Slavyanka',
            'Russia':'Sochi','Russia':'Sovetskaya Gavan','Russia':'Taganrog','Russia':'Temryuk','Russia':'Tiksi','Russia':'Tuapse','Russia':'Uglegorsk','Russia':'Ust Luga','Russia':'Vitaz Marine Terminal','Russia':'Vitino','Russia':'Vladivostok','Russia':'Vostochnyy','Russia':'Vyborg','Russia':'Yeysk','Russia':'Zarubino','Saint Kitts and Nevis':'Basseterre','Saint Lucia':'Castries',
            'Saint Lucia':'Grand Cul De Sac Bay','Saint Lucia':'Vieux Fort','Slovenia':'Koper','Slovenia':'Piran','Spain':'Adra','Spain':'Aguilas','Spain':'Algeciras','Spain':'Alicante','Spain':'Almeria','Spain':'Arrecife','Spain':'Aviles','Spain':'Barcelona','Spain':'Bermeo','Spain':'Burriana','Spain':'Cadiz','Spain':'Ceuta','Spain':'El Grao','Spain':'Ferrol','Spain':'Gijon',
            'Spain':'Hornillo','Spain':'Huelva','Spain':'Ibiza','Spain':'Islas Hormigas','Spain':'La Coruna','Spain':'Las Hormigas','Spain':'Las Palmas','Spain':'Mahon','Spain':'Malaga','Spain':'Marin','Spain':'Motril','Spain':'Palamos','Spain':'Palma De Mallorca','Spain':'Puerto De Alcudia','Spain':'Puerto De Bilbao','Spain':'Puerto De Carboneras','Spain':'Puerto De Gandia',
            'Spain':'Puerto De Garrucha','Spain':'Puerto De Pasajes','Spain':'Puerto Del Rosario','Spain':'Ribadeo','Spain':'Rosas','Spain':'Rota','Spain':'Sagunto','Spain':'San Ciprian','Spain':'San Feliu De Guixols','Spain':'Santa Cruz De La Palma','Spain':'Santa Cruz De Tenerife','Spain':'Santander','Spain':'Sevilla','Spain':'Tarragona','Spain':'Torrevieja','Spain':'Valencia',
            'Spain':'Vigo','Spain':'Villagarcia De Arosa','Spain':'Villanueva Y Geltru','Svalbard':'Barentsburg','Svalbard':'Longyearbyen','Svalbard':'Ny Alesund','Sweden':'Ahus','Sweden':'Bergkvara','Sweden':'Bollstabruk','Sweden':'Bovallstrand','Sweden':'Brannfors','Sweden':'Brofjorden','Sweden':'Degerhamn','Sweden':'Domsjo','Sweden':'Falkenberg','Sweden':'Farosund',
            'Sweden':'Figeholm','Sweden':'Fjallbacka','Sweden':'Gavle','Sweden':'Goteborg','Sweden':'Grebbestad','Sweden':'Grisslehamn','Sweden':'Gumbodahamn','Sweden':'Gustavsberg','Sweden':'Gustavsvik','Sweden':'Hallstavik','Sweden':'Halmstad','Sweden':'Hargshamn','Sweden':'Harnosand','Sweden':'Helsingborg','Sweden':'Hoganas','Sweden':'Hudiksvall','Sweden':'Hunnebostrand',
            'Sweden':'Iggesund','Sweden':'Kagehamn','Sweden':'Kalmar','Sweden':'Karlsborg','Sweden':'Karlshamn','Sweden':'Karlskrona','Sweden':'Karskar','Sweden':'Klintehamn','Sweden':'Kopmanholmen','Sweden':'Kramfors','Sweden':'Landskrona','Sweden':'Limhamn','Sweden':'Lulea','Sweden':'Lunde','Sweden':'Lysekil','Sweden':'Malmo','Sweden':'Marstrand','Sweden':'Nordmaling',
            'Sweden':'Norrkoping','Sweden':'Norrsundet','Sweden':'Nykoping','Sweden':'Nynashamn','Sweden':'Obbola','Sweden':'Ornskoldsvik','Sweden':'Oskarshamn','Sweden':'Oxelosund','Sweden':'Pitea','Sweden':'Ronehamn','Sweden':'Ronneby','Sweden':'Rundvik','Sweden':'Sandarne','Sweden':'Sandhamn','Sweden':'Sandvik','Sweden':'Simrishamn','Sweden':'Skelleftehamn',
            'Sweden':'Skutskar','Sweden':'Slite','Sweden':'Soderhamn','Sweden':'Sodertalje','Sweden':'Solvesborg','Sweden':'Soraker','Sweden':'Stenungsund','Sweden':'Stocka','Sweden':'Stockholm','Sweden':'Stockvik','Sweden':'Stora Jatterson','Sweden':'Storugns','Sweden':'Stromstad','Sweden':'Sundsvall','Sweden':'Torehamn','Sweden':'Trelleborg','Sweden':'Uddevalla',
            'Sweden':'Ulvvik','Sweden':'Umea Hamn','Sweden':'Utansjo','Sweden':'Vaja','Sweden':'Vallvik','Sweden':'Varberg','Sweden':'Vasteras','Sweden':'Vastervik','Sweden':'Verkeback','Sweden':'Visby','Sweden':'Vivstavarv','Sweden':'Ystad','Tunisia':'Ashtart Oil Terminal','Tunisia':'Banzart','Tunisia':'Didon Terminal','Tunisia':'Gabes','Tunisia':'Houmt Souk',
            'Tunisia':'La Goulette','Tunisia':'Mahdia','Tunisia':'Menzel Bourguiba','Tunisia':'Mersa Sfax','Tunisia':'Rades','Tunisia':'Skhira','Tunisia':'Sousse','Tunisia':'Tabarka','Tunisia':'Tazerka Oil Terminal','Tunisia':'Tunis','Tunisia':'Zarzis','Turkey':'Aksaz Limani','Turkey':'Alanya','Turkey':'Aliaga','Turkey':'Ambarli','Turkey':'Antalya',
            'Turkey':'Antalya Offshore Terminal','Turkey':'Ayvalik','Turkey':'Bandirma','Turkey':'Bodrum','Turkey':'Borusan Fertilizer Jetty','Turkey':'Botas','Turkey':'Botas Dortyol Oil Terminal','Turkey':'Botas Natural Gas Terminal','Turkey':'Canakkale','Turkey':'Defterdar Burnu','Turkey':'Delta Terminal','Turkey':'Derince Burnu','Turkey':'Dikili',
            'Turkey':'Eceabat','Turkey':'Erdek','Turkey':'Eregli','Turkey':'Fethiye','Turkey':'Gebze','Turkey':'Gelibolu','Turkey':'Gemlik','Turkey':'Giresun','Turkey':'Golcuk Burnu','Turkey':'Gulluk','Turkey':'Haydarpasa','Turkey':'Hopa','Turkey':'Inebolu','Turkey':'Iskenderun','Turkey':'Istanbul','Turkey':'Istinye','Turkey':'Izmir','Turkey':'Izmit',
            'Turkey':'Kaba Burnu','Turkey':'Karabiga','Turkey':'Kusadasi','Turkey':'Marmaris','Turkey':'Mersin','Turkey':'Mudanya','Turkey':'Nemrut Limani Bay','Turkey':'Ordu','Turkey':'Rize','Turkey':'Samsun','Turkey':'Sinop','Turkey':'Tasucu','Turkey':'Tekirdag','Turkey':'Toros Gubre','Turkey':'Trabzon','Turkey':'Yakacik','Turkey':'Yarimca',
            'Turkey':'Zonguldak','Turks and Caicos Islands':'Cockburn Harbor','Turks and Caicos Islands':'Grand Turk','Turks and Caicos Islands':'Providenciales','U.S. Virgin Islands':'Charlotte Amalie','U.S. Virgin Islands':'Christiansted','U.S. Virgin Islands':'Cruz Bay','U.S. Virgin Islands':'Frederiksted','U.S. Virgin Islands':'Limetree Bay',
            'U.S. Virgin Islands':'Port Alucroix','Ukraine':'Alushta','Ukraine':'Balaklava','Ukraine':'Belgorod-Dnestrovsky','Ukraine':'Berdyansk','Ukraine':'Chornomors Ke','Ukraine':'Dnipro-Buzkyy','Ukraine':'Feodosiya','Ukraine':'Henichesk','Ukraine':'Illichivsk','Ukraine':'Izmayil','Ukraine':'Kerch','Ukraine':'Kherson','Ukraine':'Khorly',
            'Ukraine':'Kyrylivka','Ukraine':'Mariupol','Ukraine':'Mykolayiv','Ukraine':'Odesa','Ukraine':'Port Oktyabrsk','Ukraine':'Reni','Ukraine':'Sevastopol','Ukraine':"Skadovs'k",'Ukraine':'Sudak','Ukraine':'Ust-Dunaisk','Ukraine':'Yalta','Ukraine':'Yevpatoriya','Ukraine':'Yuzhnyy','United Kingdom':'Aberdeen','United Kingdom':'Ardglass',
            'United Kingdom':'Ardrishaig','United Kingdom':'Aultbea','United Kingdom':'Avonmouth','United Kingdom':'Ayr','United Kingdom':'Bangor','United Kingdom':'Barrow In Furness','United Kingdom':'Barry','United Kingdom':'Belfast','United Kingdom':'Berwick-Upon-Tweed','United Kingdom':'Bideford','United Kingdom':'Bird Port',
            'United Kingdom':'Blyth','United Kingdom':'Boston','United Kingdom':'Bowling','United Kingdom':'Braefoot Bay Terminal','United Kingdom':'Bridgwater','United Kingdom':'Bridlington','United Kingdom':'Bridport Harbour','United Kingdom':'Bristol','United Kingdom':'Brixham Harbour','United Kingdom':'Broadford Bay',
            'United Kingdom':'Buckie Harbor','United Kingdom':'Burghead','United Kingdom':'Burntisland','United Kingdom':'Caernarvon','United Kingdom':'Campbeltown','United Kingdom':'Cardiff','United Kingdom':'Castle Bay','United Kingdom':'Charlestown','United Kingdom':'Chatham Docks','United Kingdom':'Colchester',
            'United Kingdom':'Coleraine','United Kingdom':'Corpach','United Kingdom':'Cowes Harbour','United Kingdom':'Craignure','United Kingdom':'Crinan (Canal)','United Kingdom':'Cromarty','United Kingdom':'Dartmouth Harbour','United Kingdom':'Dover Harbor','United Kingdom':'Dunbar','United Kingdom':'Dundee',
            'United Kingdom':'Eyemouth','United Kingdom':'Falmouth Harbour','United Kingdom':'Faslane','United Kingdom':'Fawley Marine Terminal','United Kingdom':'Felixstowe','United Kingdom':'Finnart Oil Terminal','United Kingdom':'Fishguard','United Kingdom':'Fleetwood','United Kingdom':'Folkestone Harbour',
            'United Kingdom':'Fort William','United Kingdom':'Fowey Harbour','United Kingdom':'Fraserburgh Harbor','United Kingdom':'Gairloch','United Kingdom':'Garlston','United Kingdom':'Glasgow','United Kingdom':'Glensanda','United Kingdom':'Goole','United Kingdom':'Grangemouth','United Kingdom':'Granton',
            'United Kingdom':'Gravesend','United Kingdom':'Great Yarmouth','United Kingdom':'Greenock','United Kingdom':'Grimsby','United Kingdom':'Hartlepool','United Kingdom':'Harwich','United Kingdom':'Hayle','United Kingdom':'Helmsdale Harbor','United Kingdom':'Heysham','United Kingdom':'Holyhead','United Kingdom':'Hound Point Terminal','United Kingdom':'Howdendyke','United Kingdom':'Hunterston',
            'United Kingdom':'Immingham','United Kingdom':'Invergordon','United Kingdom':'Inverness','United Kingdom':'Ipswich','United Kingdom':'Isle Of Grain','United Kingdom':'Kettletoft','United Kingdom':'Kilkeel','United Kingdom':'Kilroot','United Kingdom':"King's Lynn",'United Kingdom':'Kingston Upon Hull','United Kingdom':'Kirkwall','United Kingdom':'Kyle Of Lochalsh','United Kingdom':'Kyleakin',
            'United Kingdom':'Lamlash Harbor','United Kingdom':'Lancaster','United Kingdom':'Largs','United Kingdom':'Larne','United Kingdom':'Leith','United Kingdom':'Lerwick','United Kingdom':'Littlehampton Harbour','United Kingdom':'Liverpool','United Kingdom':'Liverpool Bay Terminal','United Kingdom':'Lochaline','United Kingdom':'Lochboisdale','United Kingdom':'Lochmaddy','United Kingdom':'London',
            'United Kingdom':'Londonderry','United Kingdom':'Lossiemouth','United Kingdom':'Lowestoft','United Kingdom':'Lyness','United Kingdom':'Macduff','United Kingdom':'Mallaig','United Kingdom':'Manchester','United Kingdom':'Methil','United Kingdom':'Mevagissey','United Kingdom':'Milford Haven','United Kingdom':'Millport','United Kingdom':'Montrose','United Kingdom':'Mostyn','United Kingdom':'Neath',
            'United Kingdom':'New Holland','United Kingdom':'Newhaven Harbour','United Kingdom':'Newlyn','United Kingdom':'Newport','United Kingdom':'Oban','United Kingdom':'Old Kilpatrick','United Kingdom':'Ornsay','United Kingdom':'Padstow','United Kingdom':'Par','United Kingdom':'Penzance','United Kingdom':'Perth','United Kingdom':'Peterhead','United Kingdom':'Pierowall','United Kingdom':'Plockton',
            'United Kingdom':'Plymouth','United Kingdom':'Poole Harbour','United Kingdom':'Port Ellen','United Kingdom':'Port Talbot','United Kingdom':'Portland Harbour','United Kingdom':'Portmahomack Harbor','United Kingdom':'Portree Harbor','United Kingdom':'Portsmouth Harbour','United Kingdom':'Ramsgate','United Kingdom':'Renfrew','United Kingdom':'Rosyth','United Kingdom':'Rothesay Dock',
            'United Kingdom':'Rothesay Harbor','United Kingdom':'Rye Harbour','United Kingdom':'Scalloway','United Kingdom':'Scapa Bay','United Kingdom':'Scarborough','United Kingdom':'Scrabster Harbor','United Kingdom':'Seaham','United Kingdom':'Sharpness','United Kingdom':'Sheerness','United Kingdom':'Shoreham Harbour','United Kingdom':'Silloth','United Kingdom':'South Ness',
            'United Kingdom':'St Margarets Hope','United Kingdom':"St. Mary's (Scilly Isl.)",'United Kingdom':'Stornoway Harbor','United Kingdom':'Stranraer','United Kingdom':'Stromness','United Kingdom':'Sullom Voe','United Kingdom':'Sunderland','United Kingdom':'Swansea','United Kingdom':'Tarbert','United Kingdom':'Teesport','United Kingdom':'Teignmouth Harbour','United Kingdom':'Thamesport',
            'United Kingdom':'Tilbury','United Kingdom':'Tobermory','United Kingdom':'Torquay Harbour','United Kingdom':'Troon','United Kingdom':'Tynemouth','United Kingdom':'Uig','United Kingdom':'Ullapool','United Kingdom':'Warkworth Harbour','United Kingdom':'Warren Point','United Kingdom':'Watchet Harbor','United Kingdom':'Weymouth Harbour','United Kingdom':'Whitby','United Kingdom':'Whitehall',
            'United Kingdom':'Whitstable','United Kingdom':'Wick','United Kingdom':'Wisbech','United Kingdom':'Workington','United Kingdom':'Yarmouth Harbour','United States':'Brooklyn',

}

#####
emp_loc = {'Albania':'Durres','Albania':'Shengjin','Albania':'Vlores','Antigua and Barbuda':'St Johns','Aruba':'Paarden Baai - (Oranjestad)','Aruba':'Sint Nicolaas Baai','Bahamas':'Clifton Pier','Bahamas':'Cockburn Town','Bahamas':'Matthew Town',
            'Bahamas':'Nassau','Bahamas':'South Riding Point','Barbados':'Bridgetown','Belgium':'Antwerpen','Belgium':'Bruges','Belgium':'Bruxelles','Belgium':'Ghent','Belgium':'Nieuwpoort','Belgium':'Oostende','Belgium':'Zeebrugge','Bermuda':'Freeport','Bermuda':'Hamilton',
            'Bermuda':'Ireland Island','Bermuda':'St George','Bosnia and Herzegovina':'Neum','Bulgaria':'Burgas','Bulgaria':'Varna','Caribbean Netherlands':'Goto Oil Terminal','Caribbean Netherlands':'Kralendijk','Caribbean Netherlands':'Oranjestad',
            'Caribbean Netherlands':'Salina','Colombia':'Barranquilla','Colombia':'Buenaventura','Colombia':'Cartagena','Colombia':'Covenas','Colombia':'Covenas Offshore Term.','Colombia':'El Bosque','Colombia':'Mamonal','Colombia':'Pozos Colorados','Colombia':'Puerto Bolivar',
            'Colombia':'Puerto Prodeco','Colombia':'San Andres Island','Colombia':'Santa Marta','Colombia':'Tumaco','Colombia':'Turbo','Croatia':'Bakar','Croatia':'Dubrovnik','Croatia':'Dugi Rat','Croatia':'Korcula','Croatia':'Omisalj','Croatia':'Ploce','Croatia':'Pula',
            'Croatia':'Rijeka Luka','Croatia':'Rovinj','Croatia':'Senj','Croatia':'Sibenik','Croatia':'Split','Croatia':'Umag','Croatia':'Zadar','Croatia':'Zaliv Rasa','Cuba':'Antilla','Cuba':'Bahai De La Habana','Cuba':'Bahia De Sagua De Tanamo','Cuba':'Bahia Honda',
            'Cuba':'Banes','Cuba':'Baracoa','Cuba':'Cabanas','Cuba':'Caibarien','Cuba':'Cardenas','Cuba':'Casilda','Cuba':'Cayo Moa Grande','Cuba':'Ceiba Hueca','Cuba':'Cienfuegos','Cuba':'Felton','Cuba':'Guayabal','Cuba':'Isabela De Sagua','Cuba':'Jucaro','Cuba':'Manati',
            'Cuba':'Manzanillo','Cuba':'Mariel','Cuba':'Matanzas','Cuba':'Media Luna','Cuba':'Nicaro','Cuba':'Nueva Gerona','Cuba':'Nuevitas Bay','Cuba':'Palo Alto','Cuba':'Preston','Cuba':'Puerto Guantanamo','Cuba':'Puerto Padre','Cuba':'Santa Cruz del Sur','Cuba':'Santa Lucia',
            'Cuba':'Santiago De Cuba','Cuba':'Tunas De Zaza','Cuba':'Vita','Curacao':'Bullen Baai','Curacao':'Caracasbaai','Curacao':'Sint Michelsbaai','Curacao':'Willemstad','Denmark':'Abenra','Denmark':'Alborg','Denmark':'Arhus','Denmark':'Assens','Denmark':'Augustenborg','Denmark':'Bandholm','Denmark':'Christianso Harbor',
            'Denmark':'Ensted','Denmark':'Esbjerg','Denmark':'Faborg','Denmark':'Fakse Ladeplads Havn','Denmark':'Fredericia','Denmark':'Frederikshavn','Denmark':'Frederikssund','Denmark':'Frederiksvaerk','Denmark':'Grenaa Havn','Denmark':'Gulfhaven','Denmark':'Haderslev','Denmark':'Hadsund','Denmark':'Hals','Denmark':'Hanstholm',
            'Denmark':'Hasle','Denmark':'Helsingor','Denmark':'Hirtshals','Denmark':'Hobro','Denmark':'Holbaek','Denmark':'Holstebro-Stuer','Denmark':'Horsens','Denmark':'Hundested Havn','Denmark':'Kalundborg','Denmark':'Kerteminde','Denmark':'Kobenhavn','Denmark':'Koge','Denmark':'Kolding','Denmark':'Korsor',
            'Denmark':'Kyndbyvaerkets','Denmark':'Lemvig','Denmark':'Mariager','Denmark':'Marstal','Denmark':'Middelfart','Denmark':'Naestved','Denmark':'Nakskov','Denmark':'Nekso','Denmark':'Nyborg','Denmark':'Nykobing','Denmark':'Nykobing (Mor)','Denmark':'Nysted','Denmark':'Odense','Denmark':'Randers',
            'Denmark':'Ringkobing','Denmark':'Rodby Havn','Denmark':'Ronne','Denmark':'Rudkobing','Denmark':'Sakskobing','Denmark':'Skaelskor','Denmark':'Skaerbaek','Denmark':'Skagen Havn','Denmark':'Sonderborg','Denmark':'Stege','Denmark':'Stigsnaesvaerket','Denmark':'Stubbekobing','Denmark':'Studstrup',
            'Denmark':'Svendborg','Denmark':'Thisted','Denmark':'Thyboron','Denmark':'Tuborg','Denmark':'Vejle','Denmark':'Vordingborg','Dominica':'Portsmouth','Dominica':'Roseau','Dominican Republic':'Amber Cove','Dominican Republic':'Andres (Andres Lng Terminal)','Dominican Republic':'Cabo Rojo',
            'Dominican Republic':'La Romana','Dominican Republic':'Las Calderas','Dominican Republic':'Pepillo Salcedo','Dominican Republic':'Puerto De Haina','Dominican Republic':'Puerto Plata','Dominican Republic':'Puerto Viejo De Azua','Dominican Republic':'San Pedro De Macoris','Dominican Republic':'Sanchez',
            'Dominican Republic':'Santa Barbara De Samana','Dominican Republic':'Santa Cruz De Barahona','Dominican Republic':'Santo Domingo','Estonia':'Bekkeri','Estonia':'Heltermaa','Estonia':'Kunda','Estonia':'Lahesuu','Estonia':'Loksa','Estonia':'Meeruse','Estonia':'Miiduranna','Estonia':'Muuga-Port of Tallin',
            'Estonia':'Osmussaar','Estonia':'Paldiski Lounasadam','Estonia':'Paldiski Pohjasadam','Estonia':'Paljassaare','Estonia':'Parnu','Estonia':'Rohukula','Estonia':'Roomassaare','Estonia':'Saaremaa sadam','Estonia':'Sillamae','Estonia':'Vanasadam - Port of Tallinn','Estonia':'Vene-Balti','Estonia':'Virtsu',
            'Faroe Islands':'Fuglafjordur','Faroe Islands':'Klaksvik','Faroe Islands':'Runavik','Faroe Islands':'Sorvagur','Faroe Islands':'Torshavn','Faroe Islands':'Tvoroyri','Faroe Islands':'Vagur','Faroe Islands':'Vestmanna','Finland':'Ekenas','Finland':'Hamina','Finland':'Hanko','Finland':'Hellnas','Finland':'Helsinki',
            'Finland':'Himanka','Finland':'Inkoo','Finland':'Jussaro','Finland':'Kantlax','Finland':'Kaskinen','Finland':'Kemi','Finland':'Kokkola','Finland':'Kotka','Finland':'Kristinestad','Finland':'Loviisa','Finland':'Mantyluoto','Finland':'Mariehamn','Finland':'Naantali','Finland':'Nykarleby','Finland':'Oulu','Finland':'Pargas',
            'Finland':'Pietarsaari','Finland':'Pori','Finland':'Porkkala','Finland':'Porvoo','Finland':'Raahe','Finland':'Rahja','Finland':'Rauma','Finland':'Tahkoluoto','Finland':'Tolkkinen','Finland':'Tornio','Finland':'Turku','Finland':'Uto','Finland':'Uusikaupunki','Finland':'Vaasa','Finland':'Veitsiluoto','France':'Ambes',
            'France':'Antibes','France':'Bastia','France':'Bayonne','France':'Blaye','France':'Bonifacio','France':'Bordeaux','France':'Boulogne-Sur-Mer','France':'Calais','France':'Calvi','France':'Cannes','France':'Concarneau','France':'Deauville','France':'Dieppe','France':'Donges','France':'Dunkerque Port Est',
            'France':'Dunkerque Port Ouest','France':'Fecamp','France':'Fos','France':'Granville','France':'Gravelines','France':'Honfleur','France':"L'ile Rousse",'France':'La Pallice','France':'La Rochelle','France':'Le Legue','France':'Le Treport','France':'Le Verdon','France':"Les Sables D' Olonne",
            'France':'Lezardrieux','France':'Lorient','France':'Marseille','France':'Montoir','France':'Morlaix','France':'Nantes','France':'Nice','France':'Ouistreham','France':'Paimpol','France':'Pauillac','France':'Pontrieux','France':"Port D' Ajaccio",'France':'Port De Caen','France':'Port De Propriano',
            'France':'Port De Roscoff-Bloscon','France':'Port Of Le Havre','France':'Port Of Rouen','France':'Port Saint Louis Du Rhone','France':'Port-de-Bouc','France':'Port-La-Nouvelle','France':'Port-Vendres','France':'Porto Vecchio','France':'Rade De Brest','France':'Rade De Cherbourg','France':'Rochefort',
            'France':'Saint-Malo','France':'Saint-Raphael','France':'Saint-Tropez','France':'Saint-Valery-Sur-Somme','France':'Sete','France':'St Nazaire','France':'Tonnay Charente','France':'Toulon','France':'Treguier','France':'Villefranche','Georgia':'Batumi','Georgia':'Sokhumi','Georgia':'Supsa Marine Terminal',
            'Germany':'Brake','Germany':'Bremen','Germany':'Bremerhaven','Germany':'Brunsbuttel Canal Terminals','Germany':'Brunsbuttel Elbahafen','Germany':'Busum','Germany':'Butzfleth','Germany':'Cuxhaven','Germany':'Eckernforde','Germany':'Elsfleth','Germany':'Emden','Germany':'Flensburg','Germany':'Gluckstadt',
            'Germany':'Hamburg','Germany':'Heiligenhafen','Germany':'Helgoland','Germany':'Husum','Germany':'Itzehoe','Germany':'Kappeln','Germany':'Kiel','Germany':'Leer','Germany':'Lubeck','Germany':'Lubeck-Travemunde','Germany':'Neuhaus','Germany':'Neustadt','Germany':'Nordenham','Germany':'Oldenburg','Germany':'Orth',
            'Germany':'Papenburg','Germany':'Rendsburg','Germany':'Rostock','Germany':'Sassnitz','Germany':'Stralsund','Germany':'Wilhelmshaven','Germany':'Wismar','Germany':'Wolgast','Greece':'Achladi','Greece':'Aigio','Greece':'Alexandroupoli','Greece':'Andros','Greece':'Argostolion','Greece':'Astakos','Greece':'Ayios Nikolaos',
            'Greece':'Gavrio','Greece':'Iraklion','Greece':'Itea','Greece':'Kalamata','Greece':'Kali Limenes','Greece':'Kalimnos','Greece':'Katakolon','Greece':'Kavala','Greece':'Kerkira','Greece':'Khios','Greece':'Kymassi','Greece':'Lagos','Greece':'Lakki','Greece':'Lavrio','Greece':'Limin Kos','Greece':'Limin Sirou','Greece':'Megara Oil Terminal',
            'Greece':'Mesolongion','Greece':'Mikonos','Greece':'Milos','Greece':'Mitilini','Greece':'Navplio','Greece':'Neon Karlovas','Greece':'Nisos Naxos','Greece':'Ormos Aliveriou','Greece':'Patrai','Greece':'Pilos','Greece':'Piraievs','Greece':'Pithagorion','Greece':'Plomarion','Greece':'Preveza','Greece':'Rethimnon','Greece':'Rodhos',
            'Greece':'Samos','Greece':'Sitia','Greece':'Soudha','Greece':'Stratoni','Greece':'Thessaloniki','Greece':'Tsingeli','Greece':'Volos','Greece':'Yerakini','Greece':'Yithion','Grenada':"St George's",'Guadeloupe':'Basse Terre','Guadeloupe':'Gustavia','Guadeloupe':'Pointe A Pitre','Guadeloupe':'Port Louis','Guernsey':'Alderney Harbour',
            'Guernsey':'Saint Peter Port','Guernsey':'Saint Sampson','Haiti':'Cap Haitien','Haiti':'Jacmel','Haiti':'Miragoane','Haiti':'Petit Goave','Haiti':'Port Au Prince','Morocco':'El Jadida','Morocco':'El Jorf Lasfar','Morocco':'Essaouira','Morocco':'Kenitra','Morocco':'Mohammedia','Morocco':'Port D Al Hoceima','Morocco':'Port Nador',
            'Morocco':'Safi','Morocco':'Tanger','Morocco':'Tangier-Mediterranean','Netherlands':'Amsterdam','Netherlands':'Delfzijl','Netherlands':'Den Helder','Netherlands':'Dordrecht','Netherlands':'Eemshaven','Netherlands':'Europoort','Netherlands':'Hansweert','Netherlands':'Harlingen','Netherlands':'Hoek Van Holland','Netherlands':'Ijmuiden',
            'Netherlands':'Maassluis','Netherlands':'Rotterdam','Netherlands':'Scheveningen','Netherlands':'Schiedam','Netherlands':'Terneuzen','Netherlands':'Vlaardingen','Netherlands':'Vlissingen','Netherlands':'Zaandam','Norway':'Akrahamn','Norway':'Alesund','Norway':'Alta','Norway':'Andalsnes','Norway':'Andenes','Norway':'Ardalstangen',
            'Norway':'Arendal','Norway':'Ballstad','Norway':'Batsfjorden','Norway':'Berg','Norway':'Bergen','Norway':'Berlevag','Norway':'Bodo','Norway':'Brattholmen','Norway':'Bredvik','Norway':'Brettesnes','Norway':'Brevik','Norway':'Bronnoysund','Norway':'Bud','Norway':'Djupviken','Norway':'Drag','Norway':'Drammen','Norway':'Drobak',
            'Norway':'Egersund','Norway':'Espevaer','Norway':'Fagerstrand','Norway':'Farsund','Norway':'Fauske','Norway':'Fiborgtangen','Norway':'Finnsnes','Norway':'Flekkefjorden','Norway':'Floro','Norway':'Fredrikstad','Norway':'Gibostad','Norway':'Glomfjord','Norway':'Haakonsvern','Norway':'Halden','Norway':'Hammerfest',
            'Norway':'Hareid','Norway':'Haroysund','Norway':'Harstad','Norway':'Haugesund','Norway':'Hemnesberget','Norway':'Henningsvaer','Norway':'Holmestrand','Norway':'Hommelvik','Norway':'Honningsvag','Norway':'Horten','Norway':'Husnes','Norway':'Jossingfjord','Norway':'Kambo','Norway':'Karsto','Norway':'Kirkehamn',
            'Norway':'Kirkenes','Norway':'Kjerringoy','Norway':'Kjollefjorden','Norway':'Kopervik','Norway':'Korsnes','Norway':'Kragero','Norway':'Kristiansand','Norway':'Kristiansund','Norway':'Kvalsund','Norway':'Lakselv','Norway':'Langstein','Norway':'Larvik','Norway':'Leirvik','Norway':'Levanger','Norway':'Lilandsgrunnen',
            'Norway':'Litle Ballangen','Norway':'Lodingen','Norway':'Malm','Norway':'Maloy','Norway':'Mandal','Norway':'Medby','Norway':'Mehamnfjorden','Norway':'Meling','Norway':'Mo I Rana','Norway':'Molde','Norway':'Moldtustranda','Norway':'Mongstad','Norway':'Mosjoen','Norway':'Moss','Norway':'Mosterhamn','Norway':'Muruvik',
            'Norway':'Namsos','Norway':'Narvik','Norway':'Nesna','Norway':'Norheimsund','Norway':'Odda','Norway':'Oksfjord','Norway':'Olavsvern','Norway':'Ornes','Norway':'Orstav','Norway':'Oslo','Norway':'Porsgrunn','Norway':'Reine','Norway':'Rekefjord','Norway':'Risor','Norway':'Rognan','Norway':'Rorvik','Norway':'Sagvag','Norway':'Salsbruket',
            'Norway':'Sandefjorden','Norway':'Sandnes','Norway':'Sandnessjoen','Norway':'Sarpsborg','Norway':'Sauda','Norway':'Sjovegan','Norway':'Skien','Norway':'Skrova Havn','Norway':'Skudeneshavn','Norway':'Slagenstangen','Norway':'Sortland','Norway':'Sorvaer','Norway':'Stamsund','Norway':'Stavanger','Norway':'Steinkjer','Norway':'Stokkmarknes',
            'Norway':'Storsteilene','Norway':'Strandvik','Norway':'Stura','Norway':'Stusvik','Norway':'Sunndalsora','Norway':'Svelvik','Norway':'Svolvaer','Norway':'Talvik','Norway':'Tananger','Norway':'Thamshamm','Norway':'Tjotta','Norway':'Tofte','Norway':'Tonsberg','Norway':'Tranneset','Norway':'Tranoy','Norway':'Tromso','Norway':'Trondheim',
            'Norway':'Tvedestrand','Norway':'Ulvik','Norway':'Vadso','Norway':'Vaksdal','Norway':'Valloy','Norway':'Vardo','Poland':'Darlowo','Poland':'Gdansk','Poland':'Gdynia','Poland':'Kolobrzeg','Poland':'Nowy Port','Poland':'Police','Poland':'Port Polnochny','Poland':'Swinoujscie','Poland':'Szczecin','Poland':'Ustka','Portugal':'Angra Do Heroismo',
            'Portugal':'Aveiro','Portugal':'Faro','Portugal':'Figueira Da Foz','Portugal':'Funchal','Portugal':'Horta','Portugal':'Lajes','Portugal':'Lisboa','Portugal':'Oporto','Portugal':'Ponta Delgada','Portugal':'Porto De Leixoes','Portugal':'Praia De Vitoria','Portugal':'Setubal','Portugal':'Sines','Portugal':'Viana Do Castelo','Portugal':'Vila Do Porto',
            'Portugal':'Vila Real De S Antonio','Puerto Rico':'Aguadilla','Puerto Rico':'Arecibo','Puerto Rico':'Arroyo','Puerto Rico':'Bahia De Fajardo','Puerto Rico':'Bahia De Jobos','Puerto Rico':'Ensenada Honda','Puerto Rico':'Las Mareas','Puerto Rico':'Mayaguez','Puerto Rico':'Playa De Guanica','Puerto Rico':'Playa De Guayanilla','Puerto Rico':'Playa De Humacao',
            'Puerto Rico':'Playa De Ponce','Puerto Rico':'Puerto Yabucoa','Puerto Rico':'San Juan','Romania':'Basarabi','Romania':'Braila','Romania':'Cernavoda','Romania':'Constanta','Romania':'Danube-Black Sea Canal','Romania':'Galati','Romania':'Mangalia','Romania':'Medgidia','Romania':'Midia','Romania':'Sulina','Romania':'Tulcea','Russia':'Adler','Russia':'Aleksandrovsk -Sakhalinskiy',
            'Russia':'Anapa','Russia':"Arkhangels'k",'Russia':'Azov','Russia':'Baltiysk','Russia':'Bolshaya Piryu Guba','Russia':'Bukhta Gaydamak','Russia':'Bukhta Nagayeva (Magadan)','Russia':'Bukhta Vanino','Russia':'De Kastri','Russia':'Dudinka','Russia':'Gavan Vysotsk','Russia':'Gelendzhik','Russia':'Igarka','Russia':'Kaliningrad','Russia':'Kandalaksha','Russia':'Kavkaz Oil Terminal',
            'Russia':'Kholmsk','Russia':'Korsakov','Russia':'Kronshtadt','Russia':'Lazarev','Russia':'Lesogorsk','Russia':'Lomonosov','Russia':'Mezen','Russia':'Moskal Vo','Russia':'Murmansk','Russia':'Mys Abram','Russia':'Mys Rogatyy Oktyabrskiy','Russia':'Nakhodka','Russia':'Nevelsk','Russia':'Nikol Skoye','Russia':'Nikolayevsk Na Amur','Russia':'Novorossiysk','Russia':'Okhotsk Iy Reyd',
            'Russia':'Ostrovnoy Gremikha','Russia':'Petropavlovsk','Russia':'Pevek','Russia':'Poronaysk','Russia':'Port Beringovsky','Russia':'Port Dikson','Russia':"Pos'yet",'Russia':'Primorsk','Russia':'Provideniya','Russia':'Rabocheostrovsk','Russia':'Rostov-Na-Donu','Russia':'Sankt-Peterburg','Russia':'Severodvinsk','Russia':'Shakhtersk','Russia':'Shakotan','Russia':'Slavyanka',
            'Russia':'Sochi','Russia':'Sovetskaya Gavan','Russia':'Taganrog','Russia':'Temryuk','Russia':'Tiksi','Russia':'Tuapse','Russia':'Uglegorsk','Russia':'Ust Luga','Russia':'Vitaz Marine Terminal','Russia':'Vitino','Russia':'Vladivostok','Russia':'Vostochnyy','Russia':'Vyborg','Russia':'Yeysk','Russia':'Zarubino','Saint Kitts and Nevis':'Basseterre','Saint Lucia':'Castries',
            'Saint Lucia':'Grand Cul De Sac Bay','Saint Lucia':'Vieux Fort','Slovenia':'Koper','Slovenia':'Piran','Spain':'Adra','Spain':'Aguilas','Spain':'Algeciras','Spain':'Alicante','Spain':'Almeria','Spain':'Arrecife','Spain':'Aviles','Spain':'Barcelona','Spain':'Bermeo','Spain':'Burriana','Spain':'Cadiz','Spain':'Ceuta','Spain':'El Grao','Spain':'Ferrol','Spain':'Gijon',
            'Spain':'Hornillo','Spain':'Huelva','Spain':'Ibiza','Spain':'Islas Hormigas','Spain':'La Coruna','Spain':'Las Hormigas','Spain':'Las Palmas','Spain':'Mahon','Spain':'Malaga','Spain':'Marin','Spain':'Motril','Spain':'Palamos','Spain':'Palma De Mallorca','Spain':'Puerto De Alcudia','Spain':'Puerto De Bilbao','Spain':'Puerto De Carboneras','Spain':'Puerto De Gandia',
            'Spain':'Puerto De Garrucha','Spain':'Puerto De Pasajes','Spain':'Puerto Del Rosario','Spain':'Ribadeo','Spain':'Rosas','Spain':'Rota','Spain':'Sagunto','Spain':'San Ciprian','Spain':'San Feliu De Guixols','Spain':'Santa Cruz De La Palma','Spain':'Santa Cruz De Tenerife','Spain':'Santander','Spain':'Sevilla','Spain':'Tarragona','Spain':'Torrevieja','Spain':'Valencia',
            'Spain':'Vigo','Spain':'Villagarcia De Arosa','Spain':'Villanueva Y Geltru','Svalbard':'Barentsburg','Svalbard':'Longyearbyen','Svalbard':'Ny Alesund','Sweden':'Ahus','Sweden':'Bergkvara','Sweden':'Bollstabruk','Sweden':'Bovallstrand','Sweden':'Brannfors','Sweden':'Brofjorden','Sweden':'Degerhamn','Sweden':'Domsjo','Sweden':'Falkenberg','Sweden':'Farosund',
            'Sweden':'Figeholm','Sweden':'Fjallbacka','Sweden':'Gavle','Sweden':'Goteborg','Sweden':'Grebbestad','Sweden':'Grisslehamn','Sweden':'Gumbodahamn','Sweden':'Gustavsberg','Sweden':'Gustavsvik','Sweden':'Hallstavik','Sweden':'Halmstad','Sweden':'Hargshamn','Sweden':'Harnosand','Sweden':'Helsingborg','Sweden':'Hoganas','Sweden':'Hudiksvall','Sweden':'Hunnebostrand',
            'Sweden':'Iggesund','Sweden':'Kagehamn','Sweden':'Kalmar','Sweden':'Karlsborg','Sweden':'Karlshamn','Sweden':'Karlskrona','Sweden':'Karskar','Sweden':'Klintehamn','Sweden':'Kopmanholmen','Sweden':'Kramfors','Sweden':'Landskrona','Sweden':'Limhamn','Sweden':'Lulea','Sweden':'Lunde','Sweden':'Lysekil','Sweden':'Malmo','Sweden':'Marstrand','Sweden':'Nordmaling',
            'Sweden':'Norrkoping','Sweden':'Norrsundet','Sweden':'Nykoping','Sweden':'Nynashamn','Sweden':'Obbola','Sweden':'Ornskoldsvik','Sweden':'Oskarshamn','Sweden':'Oxelosund','Sweden':'Pitea','Sweden':'Ronehamn','Sweden':'Ronneby','Sweden':'Rundvik','Sweden':'Sandarne','Sweden':'Sandhamn','Sweden':'Sandvik','Sweden':'Simrishamn','Sweden':'Skelleftehamn',
            'Sweden':'Skutskar','Sweden':'Slite','Sweden':'Soderhamn','Sweden':'Sodertalje','Sweden':'Solvesborg','Sweden':'Soraker','Sweden':'Stenungsund','Sweden':'Stocka','Sweden':'Stockholm','Sweden':'Stockvik','Sweden':'Stora Jatterson','Sweden':'Storugns','Sweden':'Stromstad','Sweden':'Sundsvall','Sweden':'Torehamn','Sweden':'Trelleborg','Sweden':'Uddevalla',
            'Sweden':'Ulvvik','Sweden':'Umea Hamn','Sweden':'Utansjo','Sweden':'Vaja','Sweden':'Vallvik','Sweden':'Varberg','Sweden':'Vasteras','Sweden':'Vastervik','Sweden':'Verkeback','Sweden':'Visby','Sweden':'Vivstavarv','Sweden':'Ystad','Tunisia':'Ashtart Oil Terminal','Tunisia':'Banzart','Tunisia':'Didon Terminal','Tunisia':'Gabes','Tunisia':'Houmt Souk',
            'Tunisia':'La Goulette','Tunisia':'Mahdia','Tunisia':'Menzel Bourguiba','Tunisia':'Mersa Sfax','Tunisia':'Rades','Tunisia':'Skhira','Tunisia':'Sousse','Tunisia':'Tabarka','Tunisia':'Tazerka Oil Terminal','Tunisia':'Tunis','Tunisia':'Zarzis','Turkey':'Aksaz Limani','Turkey':'Alanya','Turkey':'Aliaga','Turkey':'Ambarli','Turkey':'Antalya',
            'Turkey':'Antalya Offshore Terminal','Turkey':'Ayvalik','Turkey':'Bandirma','Turkey':'Bodrum','Turkey':'Borusan Fertilizer Jetty','Turkey':'Botas','Turkey':'Botas Dortyol Oil Terminal','Turkey':'Botas Natural Gas Terminal','Turkey':'Canakkale','Turkey':'Defterdar Burnu','Turkey':'Delta Terminal','Turkey':'Derince Burnu','Turkey':'Dikili',
            'Turkey':'Eceabat','Turkey':'Erdek','Turkey':'Eregli','Turkey':'Fethiye','Turkey':'Gebze','Turkey':'Gelibolu','Turkey':'Gemlik','Turkey':'Giresun','Turkey':'Golcuk Burnu','Turkey':'Gulluk','Turkey':'Haydarpasa','Turkey':'Hopa','Turkey':'Inebolu','Turkey':'Iskenderun','Turkey':'Istanbul','Turkey':'Istinye','Turkey':'Izmir','Turkey':'Izmit',
            'Turkey':'Kaba Burnu','Turkey':'Karabiga','Turkey':'Kusadasi','Turkey':'Marmaris','Turkey':'Mersin','Turkey':'Mudanya','Turkey':'Nemrut Limani Bay','Turkey':'Ordu','Turkey':'Rize','Turkey':'Samsun','Turkey':'Sinop','Turkey':'Tasucu','Turkey':'Tekirdag','Turkey':'Toros Gubre','Turkey':'Trabzon','Turkey':'Yakacik','Turkey':'Yarimca',
            'Turkey':'Zonguldak','Turks and Caicos Islands':'Cockburn Harbor','Turks and Caicos Islands':'Grand Turk','Turks and Caicos Islands':'Providenciales','U.S. Virgin Islands':'Charlotte Amalie','U.S. Virgin Islands':'Christiansted','U.S. Virgin Islands':'Cruz Bay','U.S. Virgin Islands':'Frederiksted','U.S. Virgin Islands':'Limetree Bay',
            'U.S. Virgin Islands':'Port Alucroix','Ukraine':'Alushta','Ukraine':'Balaklava','Ukraine':'Belgorod-Dnestrovsky','Ukraine':'Berdyansk','Ukraine':'Chornomors Ke','Ukraine':'Dnipro-Buzkyy','Ukraine':'Feodosiya','Ukraine':'Henichesk','Ukraine':'Illichivsk','Ukraine':'Izmayil','Ukraine':'Kerch','Ukraine':'Kherson','Ukraine':'Khorly',
            'Ukraine':'Kyrylivka','Ukraine':'Mariupol','Ukraine':'Mykolayiv','Ukraine':'Odesa','Ukraine':'Port Oktyabrsk','Ukraine':'Reni','Ukraine':'Sevastopol','Ukraine':"Skadovs'k",'Ukraine':'Sudak','Ukraine':'Ust-Dunaisk','Ukraine':'Yalta','Ukraine':'Yevpatoriya','Ukraine':'Yuzhnyy','United Kingdom':'Aberdeen','United Kingdom':'Ardglass',
            'United Kingdom':'Ardrishaig','United Kingdom':'Aultbea','United Kingdom':'Avonmouth','United Kingdom':'Ayr','United Kingdom':'Bangor','United Kingdom':'Barrow In Furness','United Kingdom':'Barry','United Kingdom':'Belfast','United Kingdom':'Berwick-Upon-Tweed','United Kingdom':'Bideford','United Kingdom':'Bird Port',
            'United Kingdom':'Blyth','United Kingdom':'Boston','United Kingdom':'Bowling','United Kingdom':'Braefoot Bay Terminal','United Kingdom':'Bridgwater','United Kingdom':'Bridlington','United Kingdom':'Bridport Harbour','United Kingdom':'Bristol','United Kingdom':'Brixham Harbour','United Kingdom':'Broadford Bay',
            'United Kingdom':'Buckie Harbor','United Kingdom':'Burghead','United Kingdom':'Burntisland','United Kingdom':'Caernarvon','United Kingdom':'Campbeltown','United Kingdom':'Cardiff','United Kingdom':'Castle Bay','United Kingdom':'Charlestown','United Kingdom':'Chatham Docks','United Kingdom':'Colchester',
            'United Kingdom':'Coleraine','United Kingdom':'Corpach','United Kingdom':'Cowes Harbour','United Kingdom':'Craignure','United Kingdom':'Crinan (Canal)','United Kingdom':'Cromarty','United Kingdom':'Dartmouth Harbour','United Kingdom':'Dover Harbor','United Kingdom':'Dunbar','United Kingdom':'Dundee',
            'United Kingdom':'Eyemouth','United Kingdom':'Falmouth Harbour','United Kingdom':'Faslane','United Kingdom':'Fawley Marine Terminal','United Kingdom':'Felixstowe','United Kingdom':'Finnart Oil Terminal','United Kingdom':'Fishguard','United Kingdom':'Fleetwood','United Kingdom':'Folkestone Harbour',
            'United Kingdom':'Fort William','United Kingdom':'Fowey Harbour','United Kingdom':'Fraserburgh Harbor','United Kingdom':'Gairloch','United Kingdom':'Garlston','United Kingdom':'Glasgow','United Kingdom':'Glensanda','United Kingdom':'Goole','United Kingdom':'Grangemouth','United Kingdom':'Granton',
            'United Kingdom':'Gravesend','United Kingdom':'Great Yarmouth','United Kingdom':'Greenock','United Kingdom':'Grimsby','United Kingdom':'Hartlepool','United Kingdom':'Harwich','United Kingdom':'Hayle','United Kingdom':'Helmsdale Harbor','United Kingdom':'Heysham','United Kingdom':'Holyhead','United Kingdom':'Hound Point Terminal','United Kingdom':'Howdendyke','United Kingdom':'Hunterston',
            'United Kingdom':'Immingham','United Kingdom':'Invergordon','United Kingdom':'Inverness','United Kingdom':'Ipswich','United Kingdom':'Isle Of Grain','United Kingdom':'Kettletoft','United Kingdom':'Kilkeel','United Kingdom':'Kilroot','United Kingdom':"King's Lynn",'United Kingdom':'Kingston Upon Hull','United Kingdom':'Kirkwall','United Kingdom':'Kyle Of Lochalsh','United Kingdom':'Kyleakin',
            'United Kingdom':'Lamlash Harbor','United Kingdom':'Lancaster','United Kingdom':'Largs','United Kingdom':'Larne','United Kingdom':'Leith','United Kingdom':'Lerwick','United Kingdom':'Littlehampton Harbour','United Kingdom':'Liverpool','United Kingdom':'Liverpool Bay Terminal','United Kingdom':'Lochaline','United Kingdom':'Lochboisdale','United Kingdom':'Lochmaddy','United Kingdom':'London',
            'United Kingdom':'Londonderry','United Kingdom':'Lossiemouth','United Kingdom':'Lowestoft','United Kingdom':'Lyness','United Kingdom':'Macduff','United Kingdom':'Mallaig','United Kingdom':'Manchester','United Kingdom':'Methil','United Kingdom':'Mevagissey','United Kingdom':'Milford Haven','United Kingdom':'Millport','United Kingdom':'Montrose','United Kingdom':'Mostyn','United Kingdom':'Neath',
            'United Kingdom':'New Holland','United Kingdom':'Newhaven Harbour','United Kingdom':'Newlyn','United Kingdom':'Newport','United Kingdom':'Oban','United Kingdom':'Old Kilpatrick','United Kingdom':'Ornsay','United Kingdom':'Padstow','United Kingdom':'Par','United Kingdom':'Penzance','United Kingdom':'Perth','United Kingdom':'Peterhead','United Kingdom':'Pierowall','United Kingdom':'Plockton',
            'United Kingdom':'Plymouth','United Kingdom':'Poole Harbour','United Kingdom':'Port Ellen','United Kingdom':'Port Talbot','United Kingdom':'Portland Harbour','United Kingdom':'Portmahomack Harbor','United Kingdom':'Portree Harbor','United Kingdom':'Portsmouth Harbour','United Kingdom':'Ramsgate','United Kingdom':'Renfrew','United Kingdom':'Rosyth','United Kingdom':'Rothesay Dock',
            'United Kingdom':'Rothesay Harbor','United Kingdom':'Rye Harbour','United Kingdom':'Scalloway','United Kingdom':'Scapa Bay','United Kingdom':'Scarborough','United Kingdom':'Scrabster Harbor','United Kingdom':'Seaham','United Kingdom':'Sharpness','United Kingdom':'Sheerness','United Kingdom':'Shoreham Harbour','United Kingdom':'Silloth','United Kingdom':'South Ness',
            'United Kingdom':'St Margarets Hope','United Kingdom':"St. Mary's (Scilly Isl.)",'United Kingdom':'Stornoway Harbor','United Kingdom':'Stranraer','United Kingdom':'Stromness','United Kingdom':'Sullom Voe','United Kingdom':'Sunderland','United Kingdom':'Swansea','United Kingdom':'Tarbert','United Kingdom':'Teesport','United Kingdom':'Teignmouth Harbour','United Kingdom':'Thamesport',
            'United Kingdom':'Tilbury','United Kingdom':'Tobermory','United Kingdom':'Torquay Harbour','United Kingdom':'Troon','United Kingdom':'Tynemouth','United Kingdom':'Uig','United Kingdom':'Ullapool','United Kingdom':'Warkworth Harbour','United Kingdom':'Warren Point','United Kingdom':'Watchet Harbor','United Kingdom':'Weymouth Harbour','United Kingdom':'Whitby','United Kingdom':'Whitehall',
            'United Kingdom':'Whitstable','United Kingdom':'Wick','United Kingdom':'Wisbech','United Kingdom':'Workington','United Kingdom':'Yarmouth Harbour','United States':'Brooklyn',
}

#####
port_codes = {}


#####
port_names = {'Abenra','Aberdeen','Achladi','Adler','Adra','Aguadilla','Aguilas','Ahus','Aigio','Akrahamn','Aksaz Limani','Alanya','Alborg','Alderney Harbour','Aleksandrovsk -Sakhalinskiy',
'Alesund','Alexandroupoli','Algeciras','Aliaga','Alicante','Almeria','Alta','Alushta','Ambarli','Amber Cove','Ambes','Amsterdam','Anapa','Andalsnes','Andenes','Andres (Andres Lng Terminal)',
'Andros','Angra Do Heroismo','Antalya','Antalya Offshore Terminal','Antibes','Antilla','Antwerpen','Ardalstangen','Ardglass','Ardrishaig','Arecibo','Arendal','Argostolion','Arhus',"Arkhangels'k",
'Arrecife','Arroyo','Ashtart Oil Terminal','Assens','Astakos','Augustenborg','Aultbea','Aveiro','Aviles','Avonmouth','Ayios Nikolaos','Ayr','Ayvalik','Azov','Bahai De La Habana','Bahia De Fajardo','Bahia De Jobos',
'Bahia De Sagua De Tanamo','Bahia Honda','Bakar','Balaklava','Ballstad','Baltiysk','Bandholm','Bandirma','Banes','Bangor','Banzart','Baracoa','Barcelona','Barentsburg','Barranquilla','Barrow In Furness','Barry','Basarabi','Basse Terre','Basseterre','Bastia','Batsfjorden','Batumi','Bayonne','Bekkeri','Belfast','Belgorod-Dnestrovsky','Berdyansk','Berg','Bergen','Bergkvara','Berlevag','Bermeo','Berwick-Upon-Tweed','Bideford',
'Bird Port','Blaye','Blyth','Bodo','Bodrum','Bollstabruk','Bolshaya Piryu Guba','Bonifacio','Bordeaux','Borusan Fertilizer Jetty','Boston','Botas','Botas Dortyol Oil Terminal',
'Botas Natural Gas Terminal','Boulogne-Sur-Mer','Bovallstrand','Bowling','Braefoot Bay Terminal','Braila','Brake','Brannfors','Brattholmen','Bredvik','Bremen','Bremerhaven','Brettesnes','Brevik','Bridgetown',
'Bridgwater','Bridlington','Bridport Harbour','Bristol','Brixham Harbour','Broadford Bay','Brofjorden','Bronnoysund','Brooklyn','Bruges','Brunsbuttel Canal Terminals','Brunsbuttel Elbahafen','Bruxelles','Buckie Harbor','Bud','Buenaventura','Bukhta Gaydamak','Bukhta Nagayeva (Magadan)','Bukhta Vanino','Bullen Baai',
'Burgas','Burghead','Burntisland','Burriana','Busum','Butzfleth','Cabanas','Cabo Rojo','Cadiz','Caernarvon','Caibarien','Calais','Calvi','Campbeltown','Canakkale','Cannes','Cap Haitien','Caracasbaai','Cardenas','Cardiff','Cartagena','Casilda','Castle Bay','Castries','Cayo Moa Grande','Ceiba Hueca','Cernavoda','Ceuta',
'Charlestown','Charlotte Amalie','Chatham Docks','Chornomors Ke','Christianso Harbor','Christiansted',
'Cienfuegos','Clifton Pier','Cockburn Harbor','Cockburn Town','Colchester','Coleraine','Concarneau','Constanta','Corpach','Covenas','Covenas Offshore Term.','Cowes Harbour','Craignure',
'Crinan (Canal)','Cromarty','Cruz Bay','Cuxhaven','Danube-Black Sea Canal','Darlowo','Dartmouth Harbour','De Kastri','Deauville','Defterdar Burnu','Degerhamn','Delfzijl','Delta Terminal','Den Helder',
'Derince Burnu','Didon Terminal','Dieppe','Dikili','Djupviken','Dnipro-Buzkyy','Domsjo','Donges','Dordrecht','Dover Harbor','Drag','Drammen','Drobak','Dubrovnik',
'Dudinka','Dugi Rat','Dunbar','Dundee','Dunkerque Port Est','Dunkerque Port Ouest','Durres','Eceabat','Eckernforde','Eemshaven','Egersund','Ekenas','El Bosque','El Grao','El Jadida','El Jorf Lasfar','Elsfleth','Emden',
'Ensenada Honda','Ensted','Erdek','Eregli','Esbjerg','Espevaer','Essaouira','Europoort','Eyemouth','Faborg','Fagerstrand','Fakse Ladeplads Havn','Falkenberg','Falmouth Harbour','Faro','Farosund','Farsund','Faslane','Fauske','Fawley Marine Terminal','Fecamp','Felixstowe','Felton','Feodosiya','Ferrol','Fethiye',
'Fiborgtangen','Figeholm','Figueira Da Foz','Finnart Oil Terminal','Finnsnes','Fishguard','Fjallbacka','Fleetwood','Flekkefjorden','Flensburg','Floro','Folkestone Harbour','Fort William','Fos','Fowey Harbour','Fraserburgh Harbor','Fredericia','Frederikshavn','Frederikssund','Frederiksted',
'Frederiksvaerk','Fredrikstad','Freeport','Fuglafjordur','Funchal','Gabes','Gairloch','Galati','Garlston','Gavan Vysotsk','Gavle','Gavrio','Gdansk','Gdynia','Gebze','Gelendzhik','Gelibolu','Gemlik',
'Ghent','Gibostad','Gijon','Giresun','Glasgow','Glensanda','Glomfjord','Gluckstadt','Golcuk Burnu','Goole','Goteborg','Goto Oil Terminal','Grand Cul De Sac Bay','Grand Turk','Grangemouth','Granton','Granville','Gravelines','Gravesend','Great Yarmouth','Grebbestad','Greenock','Grenaa Havn','Grimsby','Grisslehamn',
'Guayabal','Gulfhaven','Gulluk','Gumbodahamn','Gustavia','Gustavsberg','Gustavsvik','Haakonsvern','Haderslev','Hadsund','Halden','Hallstavik','Halmstad','Hals','Hamburg','Hamilton',
'Hamina','Hammerfest','Hanko','Hanstholm','Hansweert','Hareid','Hargshamn','Harlingen','Harnosand','Haroysund','Harstad','Hartlepool','Harwich','Hasle','Haugesund','Haydarpasa','Hayle','Heiligenhafen','Helgoland',
'Hellnas','Helmsdale Harbor','Helsingborg','Helsingor','Helsinki','Heltermaa','Hemnesberget','Henichesk','Henningsvaer','Heysham','Himanka','Hirtshals','Hobro','Hoek Van Holland','Hoganas','Holbaek','Holmestrand','Holstebro-Stuer','Holyhead','Hommelvik','Honfleur','Honningsvag','Hopa','Hornillo','Horsens','Horta',
'Horten','Houmt Souk','Hound Point Terminal','Howdendyke','Hudiksvall','Huelva','Hundested Havn','Hunnebostrand',
'Hunterston','Husnes','Husum','Ibiza','Igarka','Iggesund','Ijmuiden','Illichivsk','Immingham','Inebolu','Inkoo','Invergordon','Inverness','Ipswich','Iraklion','Ireland Island',
'Isabela De Sagua','Iskenderun','Islas Hormigas','Isle Of Grain','Istanbul','Istinye','Itea','Itzehoe','Izmayil','Izmir','Izmit','Jacmel','Jossingfjord','Jucaro','Jussaro','Kaba Burnu','Kagehamn','Kalamata',
'Kali Limenes','Kalimnos','Kaliningrad','Kalmar','Kalundborg','Kambo','Kandalaksha','Kantlax','Kappeln','Karabiga','Karlsborg','Karlshamn','Karlskrona','Karskar','Karsto','Kaskinen','Katakolon','Kavala','Kavkaz Oil Terminal','Kemi','Kenitra','Kerch','Kerkira','Kerteminde','Kettletoft','Kherson','Khios','Kholmsk',
'Khorly','Kiel','Kilkeel','Kilroot',"King's Lynn",'Kingston Upon Hull','Kirkehamn','Kirkenes','Kirkwall','Kjerringoy','Kjollefjorden','Klaksvik','Klintehamn','Kobenhavn','Koge',
'Kokkola','Kolding','Kolobrzeg','Koper','Kopervik','Kopmanholmen','Korcula','Korsakov','Korsnes','Korsor','Kotka','Kragero','Kralendijk','Kramfors','Kristiansand','Kristiansund','Kristinestad','Kronshtadt','Kunda','Kusadasi','Kvalsund','Kyle Of Lochalsh','Kyleakin','Kymassi','Kyndbyvaerkets','Kyrylivka',"L'ile Rousse",
'La Coruna','La Goulette','La Pallice','La Rochelle','La Romana','Lagos','Lahesuu','Lajes','Lakki','Lakselv','Lamlash Harbor','Lancaster','Landskrona','Langstein','Largs','Larne','Larvik','Las Calderas','Las Hormigas','Las Mareas','Las Palmas','Lavrio','Lazarev','Le Legue','Le Treport','Le Verdon','Leer','Leirvik',
'Leith','Lemvig','Lerwick',"Les Sables D' Olonne",'Lesogorsk','Levanger','Lezardrieux','Lilandsgrunnen','Limetree Bay','Limhamn','Limin Kos','Limin Sirou','Lisboa','Litle Ballangen','Littlehampton Harbour','Liverpool','Liverpool Bay Terminal','Lochaline','Lochboisdale','Lochmaddy','Lodingen','Loksa','Lomonosov','London',
'Londonderry','Longyearbyen','Lorient','Lossiemouth','Loviisa','Lowestoft','Lubeck','Lubeck-Travemunde','Lulea','Lunde','Lyness','Lysekil','Maassluis','Macduff','Mahdia','Mahon','Malaga','Mallaig','Malm','Malmo','Maloy','Mamonal',
'Manati','Manchester','Mandal','Mangalia','Mantyluoto','Manzanillo','Mariager','Mariehamn','Mariel','Marin','Mariupol','Marmaris','Marseille','Marstal','Marstrand','Matanzas','Matthew Town','Mayaguez','Medby','Medgidia','Media Luna','Meeruse','Megara Oil Terminal','Mehamnfjorden','Meling','Menzel Bourguiba','Mersa Sfax',
'Mersin','Mesolongion','Methil','Mevagissey','Mezen','Middelfart','Midia','Miiduranna','Mikonos','Milford Haven','Millport','Milos','Miragoane','Mitilini','Mo I Rana','Mohammedia','Molde','Moldtustranda','Mongstad','Montoir',
'Montrose','Morlaix','Mosjoen','Moskal Vo','Moss','Mosterhamn','Mostyn','Motril','Mudanya','Murmansk','Muruvik','Muuga-Port of Tallin','Mykolayiv','Mys Abram','Mys Rogatyy Oktyabrskiy','Naantali','Naestved','Nakhodka','Nakskov','Namsos','Nantes','Narvik','Nassau','Navplio','Neath','Nekso','Nemrut Limani Bay','Neon Karlovas',
'Nesna','Neuhaus','Neum','Neustadt','Nevelsk','New Holland','Newhaven Harbour','Newlyn','Newport','Nicaro','Nice','Nieuwpoort','Nikol Skoye','Nikolayevsk Na Amur','Nisos Naxos','Nordenham','Nordmaling','Norheimsund','Norrkoping','Norrsundet','Novorossiysk','Nowy Port','Nueva Gerona','Nuevitas Bay','Ny Alesund','Nyborg','Nykarleby',
'Nykobing','Nykobing (Mor)','Nykoping','Nynashamn','Nysted','Oban','Obbola','Odda','Odense','Odesa','Okhotsk Iy Reyd','Oksfjord','Olavsvern','Old Kilpatrick','Oldenburg','Omisalj','Oostende','Oporto','Oranjestad','Ordu','Ormos Aliveriou','Ornes','Ornsay','Ornskoldsvik','Orstav','Orth','Oskarshamn','Oslo','Osmussaar','Ostrovnoy Gremikha',
'Ouistreham','Oulu','Oxelosund','Paarden Baai - (Oranjestad)','Padstow','Paimpol','Palamos','Paldiski Lounasadam','Paldiski Pohjasadam','Paljassaare','Palma De Mallorca','Palo Alto','Papenburg','Par','Pargas','Parnu','Patrai','Pauillac','Penzance','Pepillo Salcedo','Perth','Peterhead','Petit Goave','Petropavlovsk','Pevek','Pierowall','Pietarsaari',
'Pilos','Piraievs','Piran','Pitea','Pithagorion','Playa De Guanica','Playa De Guayanilla','Playa De Humacao','Playa De Ponce','Ploce','Plockton','Plomarion','Plymouth','Pointe A Pitre','Police','Ponta Delgada','Pontrieux','Poole Harbour','Pori','Porkkala','Poronaysk','Porsgrunn','Port Alucroix','Port Au Prince','Port Beringovsky',
'Port D Al Hoceima',"Port D' Ajaccio",'Port De Caen','Port De Propriano','Port De Roscoff-Bloscon',
'Port Dikson','Port Ellen','Port Louis','Port Nador','Port Of Le Havre','Port Of Rouen','Port Oktyabrsk','Port Polnochny','Port Saint Louis Du Rhone','Port Talbot','Port-de-Bouc','Port-La-Nouvelle','Port-Vendres','Portland Harbour','Portmahomack Harbor','Porto De Leixoes','Porto Vecchio','Portree Harbor','Portsmouth','Portsmouth Harbour','Porvoo',"Pos'yet",'Pozos Colorados','Praia De Vitoria','Preston','Preveza','Primorsk','Providenciales','Provideniya','Puerto Bolivar','Puerto De Alcudia',
'Puerto De Bilbao','Puerto De Carboneras','Puerto De Gandia','Puerto De Garrucha','Puerto De Haina','Puerto De Pasajes','Puerto Del Rosario','Puerto Guantanamo','Puerto Padre','Puerto Plata','Puerto Prodeco','Puerto Viejo De Azua','Puerto Yabucoa','Pula','Raahe','Rabocheostrovsk','Rade De Brest','Rade De Cherbourg','Rades','Rahja','Ramsgate',
'Randers','Rauma','Reine','Rekefjord','Rendsburg','Renfrew','Reni','Rethimnon','Ribadeo','Rijeka Luka','Ringkobing','Risor','Rize','Rochefort','Rodby Havn','Rodhos','Rognan','Rohukula','Ronehamn','Ronne','Ronneby','Roomassaare','Rorvik','Rosas','Roseau','Rostock','Rostov-Na-Donu','Rosyth','Rota','Rothesay Dock','Rothesay Harbor','Rotterdam','Rovinj',
'Rudkobing','Runavik','Rundvik','Rye Harbour','Saaremaa sadam','Safi','Sagunto','Sagvag','Saint Peter Port','Saint Sampson','Saint-Malo','Saint-Raphael','Saint-Tropez','Saint-Valery-Sur-Somme','Sakskobing','Salina','Salsbruket','Samos','Samsun','San Andres Island','San Ciprian','San Feliu De Guixols','San Juan','San Pedro De Macoris','Sanchez','Sandarne','Sandefjorden','Sandhamn','Sandnes','Sandnessjoen',
'Sandvik','Sankt-Peterburg','Santa Barbara De Samana','Santa Cruz De Barahona','Santa Cruz De La Palma','Santa Cruz De Tenerife','Santa Cruz del Sur','Santa Lucia','Santa Marta','Santander','Santiago De Cuba','Santo Domingo','Sarpsborg','Sassnitz','Sauda','Scalloway','Scapa Bay','Scarborough','Scheveningen','Schiedam','Scrabster Harbor','Seaham','Senj','Sete',
'Setubal','Sevastopol','Severodvinsk','Sevilla','Shakhtersk','Shakotan','Sharpness','Sheerness','Shengjin','Shoreham Harbour','Sibenik','Sillamae','Silloth','Simrishamn','Sines','Sinop','Sint Michelsbaai','Sint Nicolaas Baai','Sitia','Sjovegan',"Skadovs'k",'Skaelskor','Skaerbaek','Skagen Havn','Skelleftehamn','Skhira','Skien','Skrova Havn',
'Skudeneshavn','Skutskar','Slagenstangen','Slavyanka','Slite','Sochi','Soderhamn','Sodertalje','Sokhumi','Solvesborg','Sonderborg','Soraker','Sortland','Sorvaer','Sorvagur','Soudha','Sousse','South Ness','South Riding Point','Southampton','Sovetskaya Gavan','Split','St George',"St George's",'St Johns','St Margarets Hope','St Nazaire',"St. Mary's (Scilly Isl.)",
'Stamsund','Stavanger','Stege','Steinkjer','Stenungsund','Stigsnaesvaerket','Stocka','Stockholm',
'Stockvik','Stokkmarknes','Stora Jatterson','Stornoway Harbor','Storsteilene','Storugns','Stralsund','Strandvik','Stranraer','Stratoni','Stromness','Stromstad','Stubbekobing','Studstrup','Stura','Stusvik','Sudak','Sulina','Sullom Voe','Sunderland','Sundsvall','Sunndalsora','Supsa Marine Terminal','Svelvik','Svendborg','Svolvaer',
'Swansea','Swinoujscie','Szczecin','Tabarka','Taganrog','Tahkoluoto','Talvik','Tananger','Tanger','Tangier-Mediterranean','Tarbert','Tarragona','Tasucu','Tazerka Oil Terminal','Teesport','Teignmouth Harbour','Tekirdag','Temryuk','Terneuzen','Thamesport','Thamshamm','Thessaloniki','Thisted','Thyboron','Tiksi','Tilbury','Tjotta','Tobermory',
'Tofte','Tolkkinen','Tonnay Charente','Tonsberg','Torehamn','Tornio','Toros Gubre','Torquay Harbour','Torrevieja','Torshavn','Toulon','Trabzon','Tranneset','Tranoy','Treguier','Trelleborg','Tromso','Trondheim','Troon','Tsingeli','Tuapse','Tuborg','Tulcea','Tumaco','Tunas De Zaza','Tunis','Turbo','Turku','Tvedestrand','Tvoroyri','Tynemouth',
'Uddevalla','Uglegorsk','Uig','Ullapool','Ulvik','Ulvvik','Umag','Umea Hamn','Ust Luga','Ust-Dunaisk','Ustka','Utansjo','Uto','Uusikaupunki','Vaasa','Vadso','Vagur','Vaja','Vaksdal','Valencia','Valloy','Vallvik','Vanasadam - Port of Tallinn','Varberg','Vardo','Varna','Vasteras','Vastervik','Veitsiluoto','Vejle','Vene-Balti','Verkeback','Vestmanna',
'Viana Do Castelo','Vieux Fort','Vigo','Vila Do Porto','Vila Real De S Antonio','Villagarcia De Arosa','Villanueva Y Geltru','Villefranche','Virtsu','Visby','Vita','Vitaz Marine Terminal','Vitino','Vivstavarv','Vlaardingen','Vladivostok','Vlissingen','Vlores','Volos','Vordingborg','Vostochnyy','Vyborg','Warkworth Harbour','Warren Point','Watchet Harbor','Weymouth Harbour','Whitby','Whitehall','Whitstable',
'Wick','Wilhelmshaven','Willemstad','Wisbech','Wismar','Wolgast','Workington','Yakacik','Yalta','Yarimca','Yarmouth Harbour','Yerakini','Yevpatoriya','Yeysk','Yithion','Ystad','Yuzhnyy',
'Zaandam','Zadar','Zaliv Rasa','Zarubino','Zarzis','Zeebrugge','Zonguldak',}

#####
stock_loc = {'Brooklyn Warehouse #1',
             'Brooklyn Warehouse #2',
             'Brooklyn Warehouse #3',
             'Pietarsaari Warehouse #55',
             'Pori Warehouse #6',
             'Whitstable Warehouse #5',
             'Wick Warehouse #4'
}

#####
contracts = {
'ALIANCA',
'AMERICAN-PRESIDENT-LINES',
'ANTILLEAN',
'ARKAS CONTAINER TRANSPORT S.A.',
'ATLANTIC-CONTAINER-LINE',
'Compagnie Maritime d Affretement Compagnie Generale Maritime ',
'COSCO-Container-Lines',
'CROWLEY',
'EVERGREEN-LINE',
'FAR EASTERN SHIPPING COMPANY',
'GOLD-STAR-LINE-LTD',
'GREAT-WHITE-FLEET',
'GRIEG-STAR-SHIPPING',
'GRIMALDI',
'Hafiz-Darya-Shipping-Lines',
'HAMBURG-SUD',
'HANJIN-SHIPPING-CO-LTD',
'Hapag Lloyd Container Line ',
'Hoegh-Autoliners',
'HORIZON-LINES',
'HYDE-SHIPPING',
'Hyundai Merchant Marine Co., Ltd.',
'Kawasaki Kisen Kaisha, Ltd.',
'Korea Marine Transport Co. Ltd.',
'MAERSK LINE',
'Mediterranean Shipping Company',
'NAMSUNG-SHIPPING-CO-LTD',
'Nippon-Yusen-Kabushiki-Kaisha-Line',
'NSLI',
'Orient Overseas Container Line Ltd.',
'Pacific-International-Lines',
'The-Shipping-Corporation-of-India-Ltd',
'Trinity-Shipping-Line',
'TURKON-LINE-INC',
'United Arab Shipping Company Co.(S.A.G)',
'West-European-Container-Lines',
'Yang-Ming-Line Yang Ming Line',
'ZIM Integrated Shipping Services Ltd',
}

#####
roles = {
'Marine Pilot',
'Harbor Master',
'Port Engineer',
'Marine Superintendent',
'Stevedore',
'Longshoreman',
'Dockworker',
}

######
product_type = {
'Fluid',
'Powder',
'Low-Temp-Gas',
'Inert Gas',
'Condensed Liquid'
}
#####
product = {
'Ethyl Acetate',
'Propyl Glycol',
'Methyl Ether',
'Butyl Ketone',
'Octane Blend',
'Hexane Base',
'Penta Chloride',
'Tetra Bromide',
'Di Phosphate',
'Mono Sulfate',
'Nitro Amine',
'Cyano Resin',
'Chloro Hydrate',
'Bromo Fluid',
'Fluoro Agent',
'Sulfo Compound',
'Thio Solution',
'Anhydo Solv',
'Alkane Liquid',
'Vinyl Ester',
}
##########
product_price = {
'5.00',
'10.00',
'25.00',
'15.00',
'45.00'
}
barrel_code = {
'672',
'673',
'674',
'207',
'208',
'209',
'210',
'211',
'212',
'213',
'900',
'901',
'902',
'903',
'904',
'905',
'906',
'907',
'908',
'909',
'671',
'670',
'680',
'677',
'941',
'949',
'927',
'935',
'936',
'937',
'938',
'939',
'931',
'932',
'933',
'997',
'922',
'945',
'978',
'956',
'989',
'930',
'290',
'291',
'292',
'295',
'920',
'921',
'942',
'923',
'928',
'3',
'4',
'5',
'6',
'7',
}